### ISSUE TITLE
bugs ?

### ISSUE THREAD

**Issue by quasiperfect** [hollax/ArrayConfigWriter#2]
- if you try to update a existing element (not change anything) to add a comment is impossible
  maybe you should add a add_comment function
- in the write method you should test for comments before adding the empty container
  new code could look like

```
      $comment_str = '';

      if (is_array($comments) && !empty($comments))
      {
        $comment_str .= '/**';
        $comment_str .= "\n";

        foreach ($comments as $line)
        {
          $comment_str .= ' * ' . $line . "\n";
        }

        $comment_str .= '*/' . "\n\n";
      }

      if (substr($mark, 0, 1) == '\\')
      {
        $mark = substr($mark, 1);
      }

      $this->_file_content = $this->_file_content . "\n" . $comment_str . $mark . "\n";
```

**Comment by hollax** [comment]
Thanks Quasiperfect. 
Firstly, the idea is to be able to add comments to new index of the config variable added with the library. As at now, you add comment. Only when you call write() method for new index, comment can not be added when updating  existing index.

Secondly, I have added your suggestion to the new release v1.1.0, which address situation where comment block is added even when comment lines (the comments parameter) isn't specified.

Lastly I have added a new method  save() which does what the __destruct did in the previous release, it saves the updated array to file. This is automatically called by the destruct if the third parameter of the __construct() is true (which is True by default) if you change the param to false, then you will have to manually call save() method after calling write() method in order to save to file.
